[package]
name = "flvstx-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "flvstx-standalone"
path = "src/main.rs"
required-features = ["standalone"]

[features]
standalone = ["nih_plug/standalone"]

[dependencies]
nih_plug.workspace = true
nih_plug_egui.workspace = true
flvstx-core = { path = "../flvstx-core" }
flvstx-ipc = { path = "../flvstx-ipc" }
arc-swap.workspace = true
serde.workspace = true
serde_json.workspace = true
egui_commonmark = "0.20"
rustysynth = "1.3"
