[package]
name = "flvstx-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "flvstx-standalone"
path = "src/main.rs"
required-features = ["standalone"]

[features]
standalone = ["nih_plug/standalone"]

[dependencies]
nih_plug.workspace = true
nih_plug_egui.workspace = true
flvstx-core = { path = "../flvstx-core", features = ["render"] }
flvstx-ipc = { path = "../flvstx-ipc" }
arc-swap.workspace = true
serde.workspace = true
serde_json.workspace = true
egui_commonmark = "0.20"
rustysynth = "1.3"
rfd = "0.15"
raw-window-handle = "0.6"
egui-baseview = { path = "../../vendor/egui-baseview", features = ["windows_keyboard_workaround"] }

[target.'cfg(windows)'.dependencies]
windows-core = "0.62"
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_System_Com_StructuredStorage", "Win32_System_Com", "Win32_System_Ole", "Win32_System_Memory", "Win32_System_SystemServices", "Win32_System_DataExchange", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
