[package]
name = "flvstx-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug.workspace = true
nih_plug_egui.workspace = true
flvstx-core = { path = "../flvstx-core" }
flvstx-ipc = { path = "../flvstx-ipc" }
arc-swap.workspace = true
serde.workspace = true
serde_json.workspace = true
